window.BHR_DATA = {
  updatedAt: "2026-07-14",
  sources: [
    {
      name: "ClinicalTrials.gov",
      type: "Registry",
      cadence: "6h",
      reliability: "High",
      url: "https://clinicaltrials.gov/"
    },
    {
      name: "FDA",
      type: "Regulator",
      cadence: "1h",
      reliability: "High",
      url: "https://www.fda.gov/"
    },
    {
      name: "EMA",
      type: "Regulator",
      cadence: "1d",
      reliability: "High",
      url: "https://www.ema.europa.eu/"
    },
    {
      name: "PubMed",
      type: "Paper",
      cadence: "1d",
      reliability: "High",
      url: "https://pubmed.ncbi.nlm.nih.gov/"
    },
    {
      name: "bioRxiv / medRxiv",
      type: "Paper",
      cadence: "1d",
      reliability: "Medium",
      url: "https://www.biorxiv.org/"
    },
    {
      name: "Company IR / Press",
      type: "Company",
      cadence: "1h",
      reliability: "Medium",
      url: "https://www.sec.gov/edgar/search/"
    },
    {
      name: "Selected Industry Media",
      type: "Media",
      cadence: "1h",
      reliability: "Low",
      url: "https://www.fiercebiotech.com/"
    }
  ],
  signals: [
    {
      id: "demo-001",
      date: "2026-07-14",
      title: "类器官药筛平台新增肿瘤适应症追踪",
      entity: "Organoid Screening Platform",
      primaryCategory: "Biotech 技术平台",
      subCategory: "Organoids & Advanced Disease Models",
      eventType: "Platform",
      sourceType: "Company",
      sourceName: "Company IR / Press",
      sourceUrl: "https://www.sec.gov/edgar/search/",
      reliability: "Medium",
      evidenceLevel: "Medium",
      needsReview: true,
      themes: ["Organoids", "Precision Oncology", "Drug Screening"],
      tags: ["类器官", "肿瘤模型", "药筛", "精准医疗"],
      fact: "公司披露其类器官模型库新增肿瘤适应症，并计划用于候选药物体外筛选。",
      report: "公司新闻稿称该平台可缩短候选药物筛选周期。",
      inference: "需要核验是否已有外部验证数据、合作药企和可重复性指标。",
      unknown: "未见公开临床相关性数据。"
    },
    {
      id: "demo-002",
      date: "2026-07-13",
      title: "虚拟细胞模型进入多组学药物响应预测测试",
      entity: "Virtual Cell Model",
      primaryCategory: "AI Drug Discovery",
      subCategory: "Virtual Cell / Cell Foundation Models",
      eventType: "Model",
      sourceType: "Paper",
      sourceName: "bioRxiv / medRxiv",
      sourceUrl: "https://www.biorxiv.org/",
      reliability: "Medium",
      evidenceLevel: "Medium",
      needsReview: true,
      themes: ["Virtual Cell", "AI for Biology", "Multi-omics"],
      tags: ["虚拟细胞", "foundation model", "多组学", "药物响应"],
      fact: "预印本描述了基于单细胞和扰动数据训练的细胞状态预测模型。",
      report: "作者报告模型可在部分细胞类型上预测扰动后的表达变化。",
      inference: "若能接入公开 benchmark，可作为 AI Drug Discovery 的专题追踪对象。",
      unknown: "未经过同行评议，外部泛化能力未知。"
    },
    {
      id: "demo-003",
      date: "2026-07-12",
      title: "AI 设计蛋白进入湿实验验证阶段",
      entity: "Protein Design Program",
      primaryCategory: "AI Drug Discovery",
      subCategory: "Protein Design",
      eventType: "Validation",
      sourceType: "Paper",
      sourceName: "PubMed",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/",
      reliability: "High",
      evidenceLevel: "High",
      needsReview: false,
      themes: ["Protein Design", "AI for Biology"],
      tags: ["蛋白设计", "湿实验", "结构验证"],
      fact: "同行评议论文报告候选蛋白完成体外结合和稳定性验证。",
      report: "论文作者报告多个设计样本达到预设结合指标。",
      inference: "应继续追踪是否有体内数据、专利和公司转化路径。",
      unknown: "临床开发计划未知。"
    },
    {
      id: "demo-004",
      date: "2026-07-11",
      title: "液体活检产品获得监管路径更新",
      entity: "Liquid Biopsy Assay",
      primaryCategory: "Diagnostics & Precision Medicine",
      subCategory: "Liquid Biopsy",
      eventType: "Regulatory",
      sourceType: "Regulator",
      sourceName: "FDA",
      sourceUrl: "https://www.fda.gov/",
      reliability: "High",
      evidenceLevel: "High",
      needsReview: false,
      themes: ["Precision Oncology", "Diagnostics"],
      tags: ["液体活检", "早筛", "监管", "肿瘤"],
      fact: "监管来源更新了相关产品的审评或批准状态。",
      report: "公告列出产品适用场景、申请人和审评路径。",
      inference: "可加入诊断产品时间线并关联同类竞品。",
      unknown: "商业化报销进度未知。"
    },
    {
      id: "demo-005",
      date: "2026-07-10",
      title: "细胞治疗临床试验状态发生变化",
      entity: "Cell Therapy Candidate",
      primaryCategory: "Clinical & Regulatory",
      subCategory: "Clinical Trials",
      eventType: "Clinical Trial",
      sourceType: "Registry",
      sourceName: "ClinicalTrials.gov",
      sourceUrl: "https://clinicaltrials.gov/",
      reliability: "High",
      evidenceLevel: "High",
      needsReview: false,
      themes: ["Cell Therapy", "Oncology"],
      tags: ["细胞治疗", "I/II 期", "临床试验", "肿瘤"],
      fact: "注册平台显示试验状态、入组目标或终点字段发生变化。",
      report: "登记信息提供试验设计、入排标准、主要终点和研究中心。",
      inference: "状态变化可能对应入组推进、方案调整或运营更新，需要与公司公告交叉核验。",
      unknown: "未披露疗效结果。"
    },
    {
      id: "demo-006",
      date: "2026-07-09",
      title: "医院工作流 AI 工具获得新客户部署",
      entity: "Clinical Workflow AI",
      primaryCategory: "Healthcare AI",
      subCategory: "Hospital Workflow AI",
      eventType: "Commercial",
      sourceType: "Company",
      sourceName: "Company IR / Press",
      sourceUrl: "https://www.sec.gov/edgar/search/",
      reliability: "Medium",
      evidenceLevel: "Low",
      needsReview: true,
      themes: ["Healthcare AI", "Hospital Workflow"],
      tags: ["医疗 AI", "医院工作流", "商业化", "SaaS"],
      fact: "公司称其临床文书或分诊相关产品完成医院部署。",
      report: "新闻稿强调效率提升和医生工作负担下降。",
      inference: "需要确认是否有独立评估、真实世界指标和合规边界。",
      unknown: "未见合同金额和长期留存数据。"
    },
    {
      id: "demo-007",
      date: "2026-07-08",
      title: "衰老生物标志物研究新增队列数据",
      entity: "Aging Biomarker Cohort",
      primaryCategory: "Longevity & Wellness",
      subCategory: "Aging Biology",
      eventType: "Research",
      sourceType: "Paper",
      sourceName: "PubMed",
      sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/",
      reliability: "High",
      evidenceLevel: "Medium",
      needsReview: false,
      themes: ["Longevity", "Biomarkers"],
      tags: ["衰老", "biomarker", "队列", "代谢"],
      fact: "论文报告一个队列中的生物标志物与年龄相关表型有关。",
      report: "作者报告统计相关性和模型性能。",
      inference: "可纳入 Longevity 专题，但不能直接推导为干预建议。",
      unknown: "因果关系和干预可逆性未知。"
    },
    {
      id: "demo-008",
      date: "2026-07-07",
      title: "合成生物学平台披露产能扩张计划",
      entity: "Synthetic Biology Foundry",
      primaryCategory: "Biotech 技术平台",
      subCategory: "Synthetic Biology",
      eventType: "Manufacturing",
      sourceType: "Media",
      sourceName: "Selected Industry Media",
      sourceUrl: "https://www.fiercebiotech.com/",
      reliability: "Low",
      evidenceLevel: "Low",
      needsReview: true,
      themes: ["Synthetic Biology", "Biofoundry"],
      tags: ["合成生物学", "biofoundry", "产能", "制造"],
      fact: "行业媒体报道公司计划扩建自动化生物制造设施。",
      report: "报道引用公司管理层对市场需求的表述。",
      inference: "需要回到公司公告、环评或融资文件核验。",
      unknown: "实际产能、成本曲线和客户结构未知。"
    }
  ]
};
